# COLS to be used across functions

# user-info cols to aggregate data later on
users_cols = ["customer_id", "MONTH", "YEAR"]

# pre-cooked features
diff_cols = [
    "dif_pago_final_prev_month",
    "dif_pago_final_prev_2_month",
    "dif_pago_final_prev_3_month",
    "dif_consumo_prev_month",
    "dif_consumo_prev_2_month",
    "dif_consumo_prev_3_month",
    "dif_discount_prev_month",
    "dif_discount_prev_2_month",
    "dif_discount_prev_3_month",
    "dif_periodica_prev_month",
    "dif_periodica_prev_2_month",
    "dif_periodica_prev_3_month",
    "dif_aperiodica_prev_month",
    "dif_aperiodica_prev_2_month",
    "dif_aperiodica_prev_3_month",
    "dif_ajuste_prev_month",
    "dif_ajuste_prev_2_month",
    "dif_ajuste_prev_3_month",
    "service_mobile_pending_install",
    "service_fix_pending_install",
    "service_mobile_cancelled",
    "service_fix_cancelled",
    "service_mobile_pending_install_3month",
    "service_fix_pending_install_3month",
    "service_mobile_cancelled_3month",
    "service_fix_cancelled_3month",
    "service_mobile_pending_install_6month",
    "service_fix_pending_install_6month",
    "service_mobile_cancelled_6month",
    "service_fix_cancelled_6month",
]

# to-be-cooked features
transform_cols = [
    "pago_final_0",
    "consumo_0",
    "aperiodica_0",
    "periodica_0",
    "discount_0",
    "ajuste_0",
    "NUM_GB_OWNN_CURR",
    "NUM_GB_2G_CURR",
    "NUM_GB_3G_CURR",
    "NUM_GB_4G_CURR",
    "NUM_GB_5G_CURR",
    "NUM_SESS_CURR",
    "NUM_SECS_CURR",
    "PERC_SECS_TYPE_IN_CURR",
    "PERC_SECS_TYPE_OUT_CURR",
    "PERC_SECS_OWNN_CURR",
    "PERC_SECS_NATR_CURR",
    "PERC_SECS_SERV_MOBI_CURR",
    "PERC_SECS_TYPE_IN_OWNN_CURR",
    "PERC_SECS_TYPE_OUT_OWNN_CURR",
    "PERC_SECS_TYPE_IN_NATR_CURR",
    "PERC_SECS_TYPE_OUT_NATR_CURR",
    "NUM_PLAT_GMM_CURR",
    "NUM_PLAT_OMV_CURR",
    "NUM_NETW_OWNN_CURR",
    "NUM_CALL_CURR",
    "PERC_CALL_TYPE_IN_CURR",
    "PERC_CALL_TYPE_OUT_CURR",
    "PERC_CALL_OWNN_CURR",
    "PERC_CALL_NATR_CURR",
    "NUM_CALL_WEEK_CURR",
    "NUM_CALL_WEEKEND_CURR",
    "NUM_SECS_WEEK_CURR",
    "NUM_SECS_WEEKEND_CURR",
    "NUM_CALL_WEEK",
    "NUM_CALL_WEEKEND",
]

# direct-to-model features
keep_cols = [
    "NUM_DAYS_ACT",
    "order_mobile_from_new_alta",
    "MIN_DAYS_PERM_CURR",
    "PREV_FINISHED_PERM",
    "NUM_DAYS_LINE_TYPE_MAIN_POST_ACT",
    # Commented columns are date format and need to be treated in the near future
    # "CUST_BUNDLE_CURR",
    # "CUST_BUNDLE_TYPE_120D",
    # "CUST_BUNDLE_TYPE_30D",
    "Import_Rest_quota_disp",
    # "LINE_TYPE_ADDI_POST_ACT_LAST_DT",
    # "LINE_TYPE_EXTR_POST_ACT_LAST_DT",
    # "LINE_TYPE_FIXE_POST_ACT_LAST_DT",
    "LINE_TYPE_FIXE_POST_ACT_LAST_DT_D",
    # "LINE_TYPE_MAIN_POST_ACT_LAST_DT",
    # "MAX_ACTIVATION_DATE",
    "MAX_DAYS_PERM_CURR",
    # "MAX_DEACTIVATION_DATE",
    "MAX_PENALTY_AMOUNT_CURR",
    # "MIN_ACTIVATION_DATE",
    "MIN_PENALTY_AMOUNT_CURR",
    "MM_GROUP_MOB_PORT",
    "NUM_CALL_INTR_CURR",
    "NUM_CALL_NATR_CURR",
    "NUM_CALL_OWNN_CURR",
    "NUM_CALL_SERV_FIXE_CURR",
    "NUM_CALL_SERV_MOBI_CURR",
    "NUM_CALL_SERV_UNKN_CURR",
    "NUM_CALL_TYPE_IN_CURR",
    "NUM_CALL_TYPE_IN_INTR_CURR",
    "NUM_CALL_TYPE_IN_NATR_CURR",
    "NUM_CALL_TYPE_IN_OWNN_CURR",
    "NUM_CALL_TYPE_IN_SERV_FIXE_CURR",
    "NUM_CALL_TYPE_IN_SERV_MOBI_CURR",
    "NUM_CALL_TYPE_IN_SERV_UNKN_CURR",
    "NUM_CALL_TYPE_IN_WEEKEND_CURR",
    "NUM_CALL_TYPE_IN_WEEK_CURR",
    "NUM_CALL_TYPE_OUT_CURR",
    "NUM_CALL_TYPE_OUT_INTR_CURR",
    "NUM_CALL_TYPE_OUT_NATR_CURR",
    "NUM_CALL_TYPE_OUT_OWNN_CURR",
    "NUM_CALL_TYPE_OUT_SERV_FIXE_CURR",
    "NUM_CALL_TYPE_OUT_SERV_MOBI_CURR",
    "NUM_CALL_TYPE_OUT_SERV_UNKN_CURR",
    "NUM_CALL_TYPE_OUT_WEEKEND_CURR",
    "NUM_CALL_TYPE_OUT_WEEK_CURR",
    "NUM_CUSTOMER_BUNDLE_2P",
    "NUM_CUSTOMER_BUNDLE_FMC",
    "NUM_CUSTOMER_BUNDLE_MO",
    "NUM_DAYS_LINE_TYPE_FIXE_POST_ACT",
    "NUM_DISC_ACTI",
    "NUM_DISC_CURR",
    "NUM_DUR_OBJ",
    "NUM_FIX_PORT",
    "NUM_FIX_PORT_LAST_1_MONTH",
    "NUM_FIX_PORT_LAST_3_MONTHS",
    "NUM_FIX_PORT_LAST_6_MONTHS",
    "NUM_INTR_CURR",
    "NUM_LINES_POST_ACTI",
    "NUM_LINES_POST_CURR",
    "NUM_LINES_TOTA",
    "NUM_LINE_TYPE_ADDI_CURR",
    "NUM_LINE_TYPE_ADDI_POST_ACTI",
    "NUM_LINE_TYPE_ADDI_POST_CURR",
    "NUM_LINE_TYPE_ADDI_TOTA",
    "NUM_LINE_TYPE_FIXE_CURR",
    "NUM_LINE_TYPE_FIXE_POST_ACTI",
    "NUM_LINE_TYPE_FIXE_TOTA",
    "NUM_LINE_TYPE_MAIN_CURR",
    "NUM_LINE_TYPE_MAIN_POST_ACTI",
    "NUM_LINE_TYPE_MAIN_POST_CURR",
    "NUM_LINE_TYPE_MAIN_TOTA",
    "NUM_MOB_PORT",
    "NUM_MOB_PORT_LAST_1_MONTH",
    "NUM_MOB_PORT_LAST_3_MONTHS",
    "NUM_MOB_PORT_LAST_6_MONTHS",
    "NUM_MOB_PORT_REQS_LAST_1_MONTH",
    "NUM_MOB_PORT_REQS_LAST_3_MONTHS",
    "NUM_MOB_PORT_REQS_LAST_6_MONTHS",
    "NUM_MOB_PORT_TRANS_CURR",
    "NUM_NATR_CURR",
    "NUM_NETW_OSPN_CURR",
    "NUM_NETW_RAAS_CURR",
    "NUM_NETW_ROAM_CURR",
    "NUM_NETW_TMEN_CURR",
    "NUM_NETW_VODA_CURR",
    "NUM_OWNN_CURR",
    "NUM_PERM_CURR",
    "NUM_PORT_OPER_DONO_MASMOVIL_GRP_LAST_THREE_MONTHS",
    "NUM_PORT_REQS_OPER_DONO_MASMOVIL_GRP_LAST_THREE_MONTHS",
    "NUM_PREV_OBJ",
    "NUM_RAAS_CURR",
    "NUM_SECS_SERV_FIXE_CURR",
    "NUM_SECS_SERV_MOBI_CURR",
    "NUM_SECS_TYPE_IN_CURR",
    "NUM_SECS_TYPE_IN_SERV_FIXE_CURR",
    "NUM_SECS_TYPE_IN_SERV_MOBI_CURR",
    "NUM_SECS_TYPE_IN_WEEKEND_CURR",
    "NUM_SECS_TYPE_IN_WEEK_CURR",
    "NUM_SECS_TYPE_OUT_CURR",
    "NUM_SECS_TYPE_OUT_SERV_FIXE_CURR",
    "NUM_SECS_TYPE_OUT_SERV_MOBI_CURR",
    "NUM_SECS_TYPE_OUT_WEEKEND_CURR",
    "NUM_SECS_TYPE_OUT_WEEK_CURR",
    "ORDER_FIX_FROM_NEW_ALTA",
    "cust_days_since_last_fix_port",
    "cust_days_since_last_mob_port",
    "cust_max_days_between_fix_port",
    "cust_max_days_between_mob_port",
    "cust_max_months_between_fix_port",
    "cust_max_months_between_mob_port",
    "cust_min_days_between_fix_port",
    "cust_min_days_between_mob_port",
    "cust_n_fix_port",
    "cust_n_fix_recent_port",
    "order_mobile_from_migra_pre_to_post",
]

# target
target_col = ["NUM_DAYS_LINE_TYPE_FIXE_POST_DEA"]
